agent:
  podName: default
  customJenkinsLabels: default
  podRetention: "OnFailure"
  volumes:
    - type: PVC
      claimName: jenkins-agent
      mountPath: /home/jenkins
      readOnly: false

additionalAgents:
  maven:
    podName: maven
    customJenkinsLabels: maven
    image: jenkins/jnlp-agent-maven
    tag: jdk11
    volumes:
      - type: PVC
        claimName: jenkins-agent
        mountPath: /home/jenkins
        readOnly: false
    resources:
      limits:
        cpu: "1"
        memory: "2048Mi"

controller:
  adminPassword: admin
  serviceType: NodePort
  installPlugins:
    - kubernetes:1.29.0
    - workflow-aggregator:2.6
    - git:4.6.0
    - configuration-as-code:1.47
  additionalPlugins:
    - bitbucket-push-and-pull-request:2.7.0
    - atlassian-bitbucket-server-integration:2.1.3
    - blueocean-web:1.24.4
    - cloudbees-bitbucket-branch-source:2.9.7
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to MY DEMO CI\CD server.


